"""Writing a table so that another machine writes the same bytes.

Every committed CSV is regenerated by CI and diffed against what is in the repo,
which is the check that the reports still build from the predictions alone. That
check only means something while the numbers survive the trip, and most of them do
because they are sums and divisions.

The p value and its interval do not. scipy reaches the t distribution through the
platform's libm, and the same comparison came out as 0.010063775865938413 on one
machine and 0.010063775865938426 on another. A real byte difference and a
meaningless numeric one, and it failed the build.

Writing fewer digits fixes it, and it was the right thing anyway: a p value carried
to seventeen significant figures claims a precision this design does not have, which
is the argument the rest of the project makes about everything else.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# Five orders of magnitude coarser than the disagreement between platforms, and
# still finer than any figure this project reports.
DECIMALS = 10

# Decimal places are the wrong unit for a p value. Ten of them turn 7.7e-17 into a
# literal zero, which is how the strongest comparison in this project came to be
# committed as 0.0 in the table that reports it. These columns keep a floor of
# significant figures instead, and six of them sit far above the platform
# disagreement the decimal rule was written for.
SIGNIFICANT = 6
SIGNIFICANT_COLUMNS = ("p_value", "q_value")


# Below this the decimal rule stops keeping six significant figures, so the other rule
# takes over. 1e-5 rounded to ten places has five of them left.
SIGNIFICANT_BELOW = 10.0 ** -(SIGNIFICANT - 1)


def _rounded(values: pd.Series) -> pd.Series:
    """One column rounded to whichever of the two rules keeps more of it.

    Values large enough for the decimal rule are left exactly where they were, so
    adding this changes nothing that was already surviving.

    Both rules round through the interpreter rather than by scaling. Scaling asks for
    a power of ten, and a p value of 1e-18 asks for 1e23, which no float holds exactly
    and which comes out of the platform's own pow. Dividing by a scale that differs in
    its last bit gave 1.9066e-18 on one machine and 1.9066000000000003e-18 on another,
    which is a rounding step reintroducing the disagreement it exists to remove.
    """
    rounded = [
        value
        if not np.isfinite(value)
        else (
            round(value, DECIMALS)
            if abs(value) >= SIGNIFICANT_BELOW
            else float(f"{value:.{SIGNIFICANT}g}")
        )
        for value in values.to_numpy(dtype=float)
    ]
    return pd.Series(rounded, index=values.index)


def write_table(frame: pd.DataFrame, path: Path) -> Path:
    """Write one table at a precision that regenerates identically elsewhere.

    Every committed CSV goes through here, so none of them can quietly reintroduce
    the platform dependent last digit the reproduce job exists to catch.
    """
    rounded = frame.round(DECIMALS)
    for column in SIGNIFICANT_COLUMNS:
        if column in frame.columns:
            rounded[column] = _rounded(frame[column])
    rounded.to_csv(path, index=False)
    return path
