"""Writing a table so that another machine writes the same bytes.

Every committed CSV is regenerated by CI and diffed against what is in the repo,
which is the check that the reports still build from the predictions alone. That
check only means something while the numbers survive the trip, and most of them do
because they are sums and divisions.

The p value and its interval do not. scipy reaches the t distribution through the
platform's libm, and the same comparison came out as 0.010063775865938413 on one
machine and 0.010063775865938426 on another. A real byte difference and a
meaningless numeric one, and it failed the build.

Writing fewer digits fixes it, and it was the right thing anyway: a p value carried
to seventeen significant figures claims a precision this design does not have, which
is the argument the rest of the project makes about everything else.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

# Five orders of magnitude coarser than the disagreement between platforms, and
# still finer than any figure this project reports.
DECIMALS = 10


def write_table(frame: pd.DataFrame, path: Path) -> Path:
    """Write one table at a precision that regenerates identically elsewhere.

    Every committed CSV goes through here, so none of them can quietly reintroduce
    the platform dependent last digit the reproduce job exists to catch.
    """
    frame.round(DECIMALS).to_csv(path, index=False)
    return path
